language: node_js
sudo: required
node_js:
  - "node"
deploy:
  - skip_cleanup: true
    provider: script
    script:
        - cd website 
        - GIT_USER=vishwa306 CURRENT_BRANCH=master yarn run publish-gh-pages
    on:
      branch: master
